name: clean_architecture_flutter
description: A reusable and scalable clean architecture template for Flutter projects.
version: 0.1.0
homepage: https://github.com/Muhammad-Zaripov/flutter_clean_architecture
repository: https://github.com/Muhammad-Zaripov/flutter_clean_architecture
issue_tracker: https://github.com/Muhammad-Zaripov/flutter_clean_architecture/issues

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/svg/
    - assets/fonts/