name: flutter_clean_architecture
description: A complete Flutter Clean Architecture template with ready-to-use folder structure and best practices.
homepage: https://github.com/Muhammad-Zaripov/flutter_clean_architecture
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/svg/
    - assets/fonts/
    

