name: clean_architecture_flutter
description: A reusable and scalable clean architecture template for Flutter projects.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/svg/
    - assets/fonts/